name: Unit Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '21' ]

    name: Test on JDK ${{ matrix.java }}

    services:
      postgres:
        image: postgres
        ports:
          - 5555:5432
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql user: admin
          postgresql password: admin
      - name: Run unit tests
        run: mvn test
